providers:
  swarm:
    exposedByDefault: false
    watch: true
  docker:
    exposedByDefault: false
    watch: true
    network: dokploy-network
  file:
    directory: /etc/dokploy/traefik/dynamic  # << CHANGE THIS
    watch: true
entryPoints:
  traefik:
    address: ':8080'
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
    http3:
      advertisedPort: 443
    http:
      tls:
        certResolver: letsencrypt
api:
  insecure: false
certificatesResolvers:
  letsencrypt:
    acme:
      email: example@gmail.com  # << CHANGE THIS
      storage: /etc/dokploy/traefik/dynamic/acme.json  # << CHANGE THIS
      httpChallenge:
        entryPoint: web